#!/bin/bash

GOVERREPO="$HOME/.goversion"
CURRENT="$GOVERREPO/current"

function init_repo() {
    if [ ! -d $GOVERREPO ]; then
        mkdir -p $GOVERREPO
        echo "GO多版本管理仓库目录创建成功：'$GOVERREPO'"
    else 
        echo "GO多版本管理仓库目录已存在：'$GOVERREPO'"
    fi
}

function download_ver() {
    if [ -z "$1" ]; then
        echo "参数错误：必须指定一个版本号"
        exit
    fi
    local os=$(uname -s | tr '[:upper:]' '[:lower:]')
    local arch=$(uname -m)
    local baseurl="https://dl.google.com/go/go$1.$os-$arch.tar.gz"
    local filename=$GOVERREPO/$1.tar.gz
    wget -O $filename -c $baseurl
    tar -xzf $filename -C $GOVERREPO
    if [ ! -d $GOVERREPO/go ]; then
        echo "解压后的go目录不存在"
        exit
    fi
    mv $GOVERREPO/go $GOVERREPO/$1
    rm $filename
    if [ ! -d $GOVERREPO/$1 ]; then
        echo "安装 $1 版本失败，可尝试手动安装"
    else
        echo "$1 版本安装成功"
        use_ver $1
    fi
}

function use_ver() {
    if [ -z "$1" ]; then
        echo "参数错误：必须指定一个版本号"
        exit
    fi
    
    if [ ! -d $CURRENT ]; then
        # CURRENT不存在，直接创建软链接
        ln -s $GOVERREPO/$1 $CURRENT
    else 
        # 已存在则修改软链接
        ln -sF $GOVERREPO/$1 $CURRENT
    fi

    # 验证软连接指向
    if [ -L "$CURRENT" ]; then
        # target=$(readlink -f $CURRENT)
        # echo "$CURRENT -> $target"
        echo "已切换到: $1 版本"
    else
        echo "切换版本失败......"
    fi
}

function list_ver() {
    RED=$(tput setaf 1)
    RESET=$(tput sgr0)
    target=$(readlink -f $CURRENT)
    current_ver=$(basename $target)
    dirs=`ls -d $GOVERREPO/* | grep -v "current"`
    for dirname in ${dirs[*]}
    do
        ver=$(basename $dirname)
        if [ $ver == $current_ver ]; then
            echo $ver"${RED}[*]${RESET}"
        else
            echo $ver
        fi
    done
}

function show_help() {
    # echo "当前GOROOT："$GOROOT
    echo "
gover-v1.0.0 help：

    'help': 查看帮助信息
    'init': 初始化Go多版本管理仓库目录。
    'install': 下载指定的Go版本。
    'list': 查看当前安装的所有Go版本。
    'use 1.24.1': 切换到指定的Go版本。
" 
}

command=$1
if [ -z "$command" ]; then
    show_help
    exit
fi

case "$command" in
'init')
    init_repo
    exit
    ;;
'install')
    download_ver $2
    exit
    ;;
'list')
    list_ver
    exit
    ;;
'use')
    use_ver $2
    exit
    ;;
'help')
    show_help
    ;;
*)
    echo "无效的命令"
esac

